"""Camada de persistencia do historico operacional da plataforma Motiva."""

from __future__ import annotations

from .models import (
    DEFAULT_HEIGHT_LIMIT_CM,
    HEIGHT_CLASS_RANGES,
    HEIGHT_THRESHOLD_CM,
    STRICT_HEIGHT_LIMIT_CM,
    Analysis,
    AnalysisObservation,
    Alert,
    AlertEvent,
    AlertSeverity,
    AlertStatus,
    AlertType,
    Base,
    CrossSectionPosition,
    FieldConditionObservation,
    Highway,
    KmMarker,
    MowingPolygon,
    MonitoredSection,
    NdviFieldSample,
    Segment,
    exceeds_height_limit,
)
from .identity import (
    GEOMETRY_IDENTITY_GRID_DEGREES,
    AnalysisIdentity,
    geometry_fingerprint,
    geometry_identity,
    road_section_identity,
)
from .alert_repository import (
    AlertEventRepository,
    AlertRepository,
    AlertVersionConflict,
    InvalidAlertTransition,
    MonitoredSectionRepository,
)
from .alert_engine import AlertEngine, AlertEngineConfig
from .monitoring import (
    DueSection,
    MonitoringConfig,
    MonitoringRunSummary,
    MonitoringService,
)
from .repository import (
    count_analyses,
    count_history_analyses,
    delete_analysis,
    get_analysis,
    hide_all_history_analyses,
    hide_analysis_from_history,
    list_analyses,
    list_history_analyses,
    nearest_km,
    save_analysis,
)
from .session import (
    database_url,
    get_engine,
    get_session_factory,
    init_database,
    reset_engine,
    session_scope,
)

__all__ = [
    "Analysis",
    "AnalysisObservation",
    "AnalysisIdentity",
    "Alert",
    "AlertEvent",
    "AlertEventRepository",
    "AlertEngine",
    "AlertEngineConfig",
    "AlertRepository",
    "AlertVersionConflict",
    "AlertSeverity",
    "AlertStatus",
    "AlertType",
    "Base",
    "CrossSectionPosition",
    "DEFAULT_HEIGHT_LIMIT_CM",
    "FieldConditionObservation",
    "HEIGHT_CLASS_RANGES",
    "HEIGHT_THRESHOLD_CM",
    "Highway",
    "KmMarker",
    "InvalidAlertTransition",
    "MowingPolygon",
    "MonitoredSection",
    "MonitoredSectionRepository",
    "MonitoringConfig",
    "MonitoringRunSummary",
    "MonitoringService",
    "DueSection",
    "NdviFieldSample",
    "STRICT_HEIGHT_LIMIT_CM",
    "Segment",
    "count_analyses",
    "count_history_analyses",
    "database_url",
    "delete_analysis",
    "exceeds_height_limit",
    "get_analysis",
    "get_engine",
    "get_session_factory",
    "geometry_fingerprint",
    "geometry_identity",
    "GEOMETRY_IDENTITY_GRID_DEGREES",
    "init_database",
    "hide_all_history_analyses",
    "hide_analysis_from_history",
    "list_analyses",
    "list_history_analyses",
    "nearest_km",
    "reset_engine",
    "road_section_identity",
    "save_analysis",
    "session_scope",
]
