/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/validate-geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Geometry */
        post: operations["validate_geometry_api_analyses_validate_geometry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_api_analyses_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}/artifacts/{artifact_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_analyses__analysis_id__artifacts__artifact_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Analysis Id */
            analysis_id: string;
            /** Status */
            status: string;
            recommendation: components["schemas"]["RecommendationResponse"];
            /** Aoi */
            aoi: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Timeseries */
            timeseries: {
                [key: string]: unknown;
            }[];
            /** Scenes */
            scenes: {
                [key: string]: unknown;
            }[];
            /** Artifacts */
            artifacts: {
                [key: string]: string;
            };
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
        };
        /** AnalysisRunRequest */
        AnalysisRunRequest: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Max Cloud Cover
             * @default 30
             */
            max_cloud_cover: number;
            /**
             * Max Scenes
             * @default 12
             */
            max_scenes: number;
            /**
             * Scene Order
             * @default newest
             * @enum {string}
             */
            scene_order: "newest" | "oldest";
            /**
             * Min Valid Pixel Percentage
             * @default 70
             */
            min_valid_pixel_percentage: number;
            /**
             * Min Observations
             * @default 4
             */
            min_observations: number;
            /**
             * Daily Aggregation
             * @default best
             * @enum {string}
             */
            daily_aggregation: "best" | "median" | "none";
            decision?: components["schemas"]["DecisionParameters"];
        };
        /** Centroid */
        Centroid: {
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
        };
        /** DecisionParameters */
        DecisionParameters: {
            /**
             * Decision Min Observations
             * @default 4
             */
            decision_min_observations: number;
            /**
             * High Vegetation Percentile
             * @default 75
             */
            high_vegetation_percentile: number;
            /**
             * Significant Drop Absolute
             * @default 0.06
             */
            significant_drop_absolute: number;
            /**
             * Significant Drop Relative Percentage
             * @default 15
             */
            significant_drop_relative_percentage: number;
            /**
             * Trend Window
             * @default 3
             */
            trend_window: number;
            /**
             * Max Gap Days
             * @default 20
             */
            max_gap_days: number;
            /**
             * Recent Intervention Days
             * @default 20
             */
            recent_intervention_days: number;
        };
        /** GeometryRequest */
        GeometryRequest: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** GeometryValidationResponse */
        GeometryValidationResponse: {
            /** Valid */
            valid: boolean;
            /** Geometry Type */
            geometry_type: string;
            /** Area Square Meters */
            area_square_meters: number;
            centroid: components["schemas"]["Centroid"];
            /** Bounding Box */
            bounding_box: number[];
            /** Estimated Sentinel Pixels */
            estimated_sentinel_pixels: number;
            /** Warnings */
            warnings: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "cortar" | "nao_cortar" | "inconclusivo";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Experimental */
            experimental: boolean;
            /** Summary */
            summary: string;
            /** Reasons */
            reasons: string[];
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Limitations */
            limitations: string[];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    validate_geometry_api_analyses_validate_geometry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeometryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_analyses_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_analyses__analysis_id__artifacts__artifact_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
                artifact_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
