/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/validate-geometry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Geometry */
        post: operations["validate_geometry_api_analyses_validate_geometry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_api_analyses_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}/artifacts/{artifact_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_analyses__analysis_id__artifacts__artifact_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisPeriodResponse */
        AnalysisPeriodResponse: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Timezone */
            timezone: string;
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "previous_calendar_month" | "explicit";
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Analysis Id */
            analysis_id: string;
            /** Status */
            status: string;
            recommendation: components["schemas"]["RecommendationResponse"];
            height_estimation: components["schemas"]["HeightEstimationResponse"];
            analysis_period: components["schemas"]["AnalysisPeriodResponse"];
            /** Selected Area M2 */
            selected_area_m2?: number | null;
            /** Effective Analysis Area M2 */
            effective_analysis_area_m2?: number | null;
            /** Effective Analysis Pct */
            effective_analysis_pct?: number | null;
            /** Aoi */
            aoi: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Timeseries */
            timeseries: {
                [key: string]: unknown;
            }[];
            /** Scenes */
            scenes: {
                [key: string]: unknown;
            }[];
            /** Artifacts */
            artifacts: {
                [key: string]: string;
            };
            /** Warnings */
            warnings: {
                [key: string]: unknown;
            }[];
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
        };
        /** AnalysisRunRequest */
        AnalysisRunRequest: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Max Cloud Cover */
            max_cloud_cover?: number | null;
            /** Max Scenes */
            max_scenes?: number | null;
            /** Scene Order */
            scene_order?: ("newest" | "oldest") | null;
            /** Min Valid Pixel Percentage */
            min_valid_pixel_percentage?: number | null;
            /** Min Observations */
            min_observations?: number | null;
            /** Daily Aggregation */
            daily_aggregation?: ("best" | "median" | "none") | null;
            decision?: components["schemas"]["DecisionParameters"] | null;
        };
        /** Centroid */
        Centroid: {
            /** Longitude */
            longitude: number;
            /** Latitude */
            latitude: number;
        };
        /** DecisionParameters */
        DecisionParameters: {
            /** Decision Min Observations */
            decision_min_observations?: number | null;
            /** High Vegetation Percentile */
            high_vegetation_percentile?: number | null;
            /** Significant Drop Absolute */
            significant_drop_absolute?: number | null;
            /** Significant Drop Relative Percentage */
            significant_drop_relative_percentage?: number | null;
            /** Trend Window */
            trend_window?: number | null;
            /** Max Gap Days */
            max_gap_days?: number | null;
            /** Recent Intervention Days */
            recent_intervention_days?: number | null;
        };
        /** GeometryRequest */
        GeometryRequest: {
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
        };
        /** GeometryValidationResponse */
        GeometryValidationResponse: {
            /** Valid */
            valid: boolean;
            /** Geometry Type */
            geometry_type: string;
            /** Area Square Meters */
            area_square_meters: number;
            centroid: components["schemas"]["Centroid"];
            /** Bounding Box */
            bounding_box: number[];
            /** Estimated Sentinel Pixels */
            estimated_sentinel_pixels: number;
            /** Warnings */
            warnings: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** HeightEstimationResponse */
        HeightEstimationResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "experimental" | "unavailable" | "disabled";
            /** Estimated Class */
            estimated_class: ("le_30_cm" | "gt_30_cm" | "inconclusive") | null;
            /** Score Gt 30 Cm */
            score_gt_30_cm?: number | null;
            /**
             * Probability Gt 30 Cm
             * @deprecated
             * @description Deprecated alias of score_gt_30_cm; not calibrated probability.
             */
            probability_gt_30_cm?: number | null;
            /** Calibration Status */
            calibration_status?: "uncalibrated" | null;
            /** Vegetation Fraction */
            vegetation_fraction?: number | null;
            /** Height Valid Pixel Count */
            height_valid_pixel_count?: number | null;
            /** Height Total Pixel Count */
            height_total_pixel_count?: number | null;
            /** Mixed Pixel Risk */
            mixed_pixel_risk?: ("low" | "medium" | "high") | null;
            /** Confidence */
            confidence: ("low" | "medium") | null;
            /**
             * Reference Threshold Cm
             * @default 30
             * @constant
             */
            reference_threshold_cm: 30;
            /** Model Version */
            model_version: string | null;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "cortar" | "nao_cortar" | "inconclusivo";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Experimental */
            experimental: boolean;
            /** Summary */
            summary: string;
            /** Reasons */
            reasons: string[];
            /** Blocking Reasons */
            blocking_reasons: string[];
            /** Limitations */
            limitations: string[];
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    validate_geometry_api_analyses_validate_geometry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeometryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeometryValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_analyses_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_analyses__analysis_id__artifacts__artifact_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
                artifact_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
